services:
  - type: web
    name: aad
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: aad-data
      mountPath: /data
      sizeGB: 1
